### ISSUE TITLE
openssl=noverify vs openssl=no-verify

### ISSUE THREAD

**Issue by boris-arkenaar** [boxyhq/website#248]
In the docs (https://github.com/boxyhq/website/blob/main/docs/jackson/deploy/env-variables.md) both `openssl=noverify` and `openssl=no-verify` are used under `DB_URL` in the following piece of text:

> ### **DB_URL**
> The database URL to connect to. If you are using self-signed certificates then pass `sslmode=noverify` instead of  `sslmode=require` in the `DB_URL`. This is because self-signed certs will be rejected as unauthorized in strict mode. Also, set `DB_SSL=true` and `DB_SSL_REJECT_UNAUTHORIZED=false` (see env vars below for more details).
>
> Example: `postgres://postgres:postgres@localhost:5432/postgres` or `postgres://postgres:postgres@localhost:5432/postgres?sslmode=no-verify`

Which one is it? :)

**Comment by deepakprabhakara** [comment]
@boris-arkenaar Thanks for spotting this, we'll fix this. It's `no-verify` :)
