### ISSUE TITLE
Deploy on Vercel

### ISSUE THREAD

**Issue by boris-arkenaar** [boxyhq/website#249]
How to configure the environment variables when deploying on Vercel? Maybe add some documentation on it?

I've figured most of it out already. Specifically, I'm still not sure how to configure SMTP though.

SMTP_HOST
SMTP_PORT
SMTP_USER
SMTP_PASSWORD
SMTP_FROM

**Comment by deepakprabhakara** [comment]
@boris-arkenaar The env vars are documented here - https://boxyhq.com/docs/jackson/deploy/env-variables. SMTP details are used for magic link login to the Admin Portal, you can use any email provider for this. We use next-auth underneath.
